### ISSUE TITLE
Edit person view should allow organizers to change a user's role

### ISSUE THREAD

**Issue by nateberkopec** [NYCrb/cfp-app#5]

**Comment by stratigos** [comment]
Looking into this issue now.

**Comment by stratigos** [comment]
After looking into this issue for some time, I am not sure if the Edit Person view (`/admin/people/<id>/edit`) is the best place for this change. The `:role` is determined by Person's many Participant dependents, which are in turn related to Events. It seems as though `:role` should be changed on a per-Event basis (or per-Participant), and isn't as suitable for the Edit Person view. Note that there already exists the ability to change the role via the Show Event view.

@nateberkopec - What I could do is, within Edit Person, list all Participant records' role, and their Event name for clarity. A select option for each could allow for 'reviewer' or 'organizer', which would update the corresponding Participant on change. This may increase the UX complexity. Does that sound suitable? Or would you prefer to only edit the Participant `:role` through the Event view (leave it as is)? 

If a Person is the one and only organizer of an Event, and this is switched to a reviewer from Edit Person view, that Event would no longer have an organizer. This could be prevented with some biz logic that simply prevents such a change if the Event has no other organizers.

Its possible that I may be misunderstanding the relations here, and would love help from anyone in clarifying this situation, if I am way off.

**Comment by nateberkopec** [comment]
> It seems as though :role should be changed on a per-Event basis (or per-Participant), and isn't as suitable for the Edit Person view

Ahhhhh, maybe that isn't appropriate for us. How difficult do you think it might be to change this? For a local user group like us, per-event permissions are overkill.

**Comment by stratigos** [comment]
@nateberkopec Thanks for the reply. I'm not sure I follow fully, though. I may not have been clear: there already exists the ability to change `:role` on a per-Event basis. At the bottom of the Show Event view, there is a list of Participants, with a 'Change Role' option for each Participant. So the per-event role update already exists.

My suggestion to also add this ability to Edit Person was just there so I have something to offer :smiley:. Truthfully I feel it adds complexity to the experience, and also may require additional business logic to ensure an Event is not left with 0 organizers.

How difficult? I don't think this change would be difficult (adding all Person's Participants' roles to Edit Person). This amounts to multiple places within the application to edit Participant's roles for Events. As an end user, I feel it may be confusing or complex.

I think the presence of the 'Role' column in the people index is actually misleading, and is what causes a user of the system to want to change `:role` via Edit Person. Since a Person has many roles through Participant, I dont see the use in listing a single role there. 

If you feel the suggested change to Edit Person would be useful, then let me know, and Ill implement it :smile:.

**Comment by nateberkopec** [comment]
>  I may not have been clear: there already exists the ability to change :role on a per-Event basis. 

My idea is that instead of the roles changing on a per-event basis, we _remove_ that feature and make roles a simple Person property.

**Comment by stratigos** [comment]
Ahh OK now I understand, Ill look into that.

**Comment by nateberkopec** [comment]
Or alternatively, you could _add_ a "global role" that overrides any event specific role.

**Comment by stratigos** [comment]
Thanks, I like the sound of that, it seems like a less intrusive change.

**Comment by nateberkopec** [comment]
Closed by #9
